apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
commonLabels:         
  rhtap/gitops: wnalwywyt-python 
  janus-idp.io/tekton: wnalwywyt-python
  backstage.io/kubernetes-id: wnalwywyt-python
  backstage.io/kubernetes-namespace: rhtap-app 
  app.kubernetes.io/part-of: wnalwywyt-python
resources: 
- application-dev.yaml 
- application-stage.yaml 
- application-prod.yaml  